[server]
enableStaticServing = true

[theme]
base = "light"

[[theme.fontFaces]]
family = "New Athena Unicode"
#url = "greekinator/static/newathu5_5.ttf"
src = "url('/static/newathu5_5.ttf') format('truetype')"
weight = 400
style = "normal"
