[server]
enableStaticServing = true

[theme]
#base="light"
#primaryColor="#F63366"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
#font="sans serif"

[[theme.fontFaces]]
family = "New Athena Unicode"
url = "greekinator/static/newathu5_5.ttf"
weight = 400
style = "normal"
