[theme]
font = "New Athena Unicode version 2018"

[[theme.fontFaces]]
family="New Athena Unicode version 2018"
src="url('https://www.classicalstudies.org/sites/default/files/userfiles/files/NAU5_005woff.zip')"
weight="400"
