[server]
enableStaticServing = true



[[theme.fontFaces]]
family = "New Athena Unicode"

url = "https://db.onlinewebfonts.com/t/636436091e8572de5ab7c1be78f0090e.woff2"
weight = 400
style = "normal"


 #"url('greekinator/static/NewAthenaUnicode.woff2') format('woff2'), 
 #     "url('greekinator/static/newathu5_5.woff') format('woff'), 
 #     "url('greekinator/static/newathu5_5.ttf') format('truetype')"
# "greekinator/static/New Athena Unicode V1.woff2" format('woff2'),
#"greekinator/static/NewAthenaUnicode.woff2"
      
[theme]
#primaryColor = "#F63366"
#backgroundColor = "black"
base = "light" #dark
font = "New Athena Unicode"
