[server]
enableStaticServing = true



[[theme.fontFaces]]
family = "New Athena Unicode"
#url = "greekinator/static/newathu5_5.ttf"
src = "url('greekinator/static/New Athena Unicode V1.woff2') format('woff2'), 
      "url('greekinator/static/NewAthenaUnicode.woff2') format('woff2'), 
      "url('greekinator/static/newathu5_5.woff') format('woff'), 
      "url('greekinator/static/newathu5_5.ttf') format('truetype')"
weight = 400
style = "normal"
fontDisplay = "swap"

[theme]
#primaryColor = "#F63366"
#backgroundColor = "black"
base = "dark" #light
font = "New Athena Unicode"
